version: "3.7"

services:
  frontend:
    build: app/frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./app/frontend:/app

  backend:
    build: app/backend
    ports:
      - 8000:8000
    volumes:
      - ./app/backend:/app
